-- ============================================================
--  ERUDITO Galery — Esquema de base de datos
--  Plataforma: Supabase (PostgreSQL)
--  Idempotente: usa CREATE TABLE IF NOT EXISTS y políticas
--  con guardas DO $$ BEGIN ... END $$.
--
--  Cambios respecto al draft original:
--    · artistas/obras/eventos → generated by default (permite seeds con IDs fijos)
--    · artistas.email         → nullable (marcas y artistas históricos sin email)
--    · eventos                → +href, +fichas_ids, +fecha_corta; modalidad incluye 'En línea'
--    · perfiles               → +avatar_url
--    · RLS habilitado en artistas, obras y eventos con lectura pública
-- ============================================================


-- ── Artistas ────────────────────────────────────────────────
create table if not exists artistas (
  id_artista      bigint primary key generated by default as identity,
  nombre          text not null,
  biografia       text,
  email           text unique,               -- nullable: marcas y artistas históricos sin email
  telefono        text,
  redes_sociales  jsonb,                     -- { ig, fb, tw, web }
  foto_perfil     text,
  vida            text,                      -- ej. "1890 – 1960"
  origen          text,                      -- ciudad / país / movimiento de origen
  especialidad    text,                      -- ej. "Expresionismo"
  fecha_registro  timestamp default current_timestamp
);

alter table artistas enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'artistas' and policyname = 'Lectura pública de artistas'
  ) then
    execute 'create policy "Lectura pública de artistas" on artistas for select using (true)';
  end if;
end $$;


-- ── Obras ────────────────────────────────────────────────────
create table if not exists obras (
  id_obra           bigint primary key generated by default as identity,
  id_artista        bigint references artistas (id_artista) on delete cascade,
  titulo            text not null,
  descripcion       text,
  precio            numeric(10, 2) not null,
  stock             int default 1,
  categoria         text,
  tecnica           text,
  dimensiones       text,
  imagen_principal  text,
  perspectivas      jsonb,                   -- ["/obras/slug/vista-1.jpg", ...]
  imagenes          jsonb,                   -- campo libre para otras URLs
  anio              text,
  movimiento        text,
  tamano            text check (tamano in ('Pequeño','Mediano','Grande')),
  color             text check (color  in ('Cálido','Frío','Neutro')),
  tipo              text check (tipo   in ('Físico','JPG Certificado','Impresión Oficial')),
  estrellas         int  check (estrellas between 1 and 5) default 5,
  grafica_valor     jsonb,                   -- [{ "mes":"Ene", "valor":36000 }] × 12
  grafica_interes   jsonb,                   -- [42, 58, 35, ...] × 7 puntos
  certificaciones   jsonb,                   -- ["Verificada...", ...]
  fecha_creacion    timestamp default current_timestamp
);

alter table obras enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'obras' and policyname = 'Lectura pública de obras'
  ) then
    execute 'create policy "Lectura pública de obras" on obras for select using (true)';
  end if;
end $$;


-- ── Perfiles (ligados a auth.users de Supabase) ─────────────
create table if not exists perfiles (
  id            uuid references auth.users (id) on delete cascade primary key,
  rol           text check (rol in ('artista','comprador','empresa')) not null,
  nombre        text        default '',
  bio           text        default '',
  especialidad  text        default '',
  pais          text        default '',
  slug          text        unique,          -- solo rol 'empresa'; ej. "mi-galeria"
  avatar_url    text        default '',      -- URL de foto de perfil en Supabase Storage
  creado_at     timestamptz default now()
);

alter table perfiles enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'perfiles' and policyname = 'Ver propio perfil') then
    execute 'create policy "Ver propio perfil" on perfiles for select using (auth.uid() = id)';
  end if;
  if not exists (select 1 from pg_policies where tablename = 'perfiles' and policyname = 'Crear propio perfil') then
    execute 'create policy "Crear propio perfil" on perfiles for insert with check (auth.uid() = id)';
  end if;
  if not exists (select 1 from pg_policies where tablename = 'perfiles' and policyname = 'Editar propio perfil') then
    execute 'create policy "Editar propio perfil" on perfiles for update using (auth.uid() = id)';
  end if;
end $$;


-- ── Eventos ─────────────────────────────────────────────────
create table if not exists eventos (
  id_evento    bigint primary key generated by default as identity,
  tipo         text check (tipo in ('Subasta','Exposición')),
  modalidad    text check (modalidad in ('Presencial','Virtual','Híbrido','En línea')),
  titulo       text not null,
  fecha        date not null,               -- ISO yyyy-mm-dd
  fecha_corta  jsonb,                       -- { "dia": "28", "mes": "Jul" }
  lugar        text,
  imagen       text,
  descripcion  text,
  href         text,                        -- ej. "/eventos/1"
  fichas_ids   jsonb                        -- [9, 10] — IDs de obras participantes
);

alter table eventos enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'eventos' and policyname = 'Lectura pública de eventos'
  ) then
    execute 'create policy "Lectura pública de eventos" on eventos for select using (true)';
  end if;
end $$;


-- ── Clientes ────────────────────────────────────────────────
create table if not exists clientes (
  id_cliente      bigint primary key generated always as identity,
  nombre          text not null,
  email           text unique not null,
  telefono        text,
  direccion       text,
  rol             text check (rol in ('artista','comprador','empresa')) default 'comprador',
  id_artista      bigint references artistas (id_artista) on delete set null,
  fecha_registro  timestamp default current_timestamp
);


-- ── Pedidos ──────────────────────────────────────────────────
create table if not exists pedidos (
  id_pedido     bigint primary key generated always as identity,
  id_cliente    bigint references clientes (id_cliente) on delete cascade,
  fecha_pedido  timestamp default current_timestamp,
  estado        text default 'Pendiente'
                  check (estado in ('Pendiente','Confirmado','Enviado','Entregado','Cancelado')),
  total         numeric(10, 2) not null
);


-- ── Detalle de pedidos ───────────────────────────────────────
create table if not exists detalle_pedidos (
  id_detalle      bigint primary key generated always as identity,
  id_pedido       bigint references pedidos (id_pedido) on delete cascade,
  id_obra         bigint references obras   (id_obra)   on delete cascade,
  cantidad        int not null,
  precio_unitario numeric(10, 2) not null
);


-- ── Servicios ────────────────────────────────────────────────
create table if not exists servicios (
  id_servicio  bigint primary key generated always as identity,
  nombre       text not null,
  descripcion  text,
  precio       numeric(10, 2),
  categoria    text check (categoria in (
    'Registro de Obras',
    'Restauración de Arte',
    'Manager de Ventas',
    'Grupo de Coleccionistas',
    'Exposición',
    'Museos y Galerías'
  ))
);


-- ── Contrataciones ──────────────────────────────────────────
create table if not exists contrataciones (
  id_contratacion    bigint primary key generated always as identity,
  id_artista         bigint references artistas  (id_artista)  on delete cascade,
  id_servicio        bigint references servicios (id_servicio) on delete cascade,
  fecha_contratacion timestamp default current_timestamp,
  estado             text default 'Activo'
                       check (estado in ('Activo','Pausado','Finalizado'))
);


-- ── Favoritos ────────────────────────────────────────────────
create table if not exists favoritos (
  id_favorito  bigint primary key generated always as identity,
  id_cliente   bigint references clientes (id_cliente) on delete cascade,
  id_obra      bigint references obras    (id_obra)    on delete cascade,
  fecha        timestamp default current_timestamp,
  unique (id_cliente, id_obra)
);


-- ── Índices ──────────────────────────────────────────────────
create index if not exists idx_obras_artista       on obras (id_artista);
create index if not exists idx_obras_movimiento    on obras (movimiento);
create index if not exists idx_obras_tamano        on obras (tamano);
create index if not exists idx_obras_color         on obras (color);
create index if not exists idx_obras_tipo          on obras (tipo);
create index if not exists idx_pedidos_cliente     on pedidos (id_cliente);
create index if not exists idx_favoritos_cliente   on favoritos (id_cliente);
create index if not exists idx_contrat_artista     on contrataciones (id_artista);
