-- ============================================================
--  ERUDITO Galery — Esquema de base de datos
--  Plataforma: Supabase (PostgreSQL)
--  Versión: 2026-09-07 (sincronizado con producción)
--
--  Idempotente: usa CREATE TABLE IF NOT EXISTS,
--  ALTER TABLE ... ADD COLUMN IF NOT EXISTS y políticas
--  con guardas DO $$ BEGIN ... END $$.
--
--  Orden de ejecución: este archivo primero, luego seeds.sql
-- ============================================================


-- ════════════════════════════════════════════════════════════
--  TABLAS PRINCIPALES
-- ════════════════════════════════════════════════════════════

-- ── Artistas ─────────────────────────────────────────────────
create table if not exists artistas (
  id_artista      bigint primary key generated by default as identity,
  nombre          text    not null,
  biografia       text,
  email           text    unique,            -- nullable: marcas/artistas históricos sin email
  telefono        text,
  redes_sociales  jsonb,                     -- { ig, fb, tw, web }
  foto_perfil     text,
  vida            text,                      -- "1890 – 1960"
  origen          text,
  especialidad    text,
  fecha_registro  timestamptz default now()
);

alter table artistas enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='artistas' and policyname='Lectura pública de artistas') then
    execute 'create policy "Lectura pública de artistas" on artistas for select using (true)';
  end if;
end $$;


-- ── Obras ─────────────────────────────────────────────────────
create table if not exists obras (
  id_obra           bigint primary key generated by default as identity,
  id_artista        bigint references artistas(id_artista) on delete set null,
  titulo            text    not null,
  descripcion       text,
  precio            numeric(10,2),
  stock             int     default 1,
  categoria         text,
  tecnica           text,
  dimensiones       text,
  imagen_principal  text,
  perspectivas      jsonb,                   -- ["url1", "url2"]
  imagenes          jsonb,
  anio              text,
  movimiento        text,
  tamano            text check (tamano in ('Pequeño','Mediano','Grande')),
  color             text check (color  in ('Cálido','Frío','Neutro')),
  tipo              text check (tipo   in ('Físico','JPG Certificado','Impresión Oficial','Edición limitada')),
  estrellas         int  check (estrellas between 1 and 5) default 5,
  grafica_valor     jsonb,                   -- [{ "mes":"Ene","valor":36000 }] × 12
  grafica_interes   jsonb,                   -- [42,58,35,...] × 7 puntos
  certificaciones   jsonb,                   -- ["Verificada autenticidad…"]
  -- columnas añadidas en producción
  vistas            int     default 0,       -- contador de visitas (RPC incrementar_vistas)
  estado            text    default 'pendiente'
                      check (estado in ('pendiente','aprobada','rechazada')),
  artista_email     text,                    -- email artista de plataforma (tabla usuarios)
  empresa_email     text,                    -- email galería/empresa (tabla usuarios)
  nombre_artista    text,                    -- artista representado por empresa
  fecha_creacion    timestamptz default now()
);

alter table obras enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='obras' and policyname='Lectura pública de obras') then
    execute 'create policy "Lectura pública de obras" on obras for select using (true)';
  end if;
end $$;


-- ── Eventos ───────────────────────────────────────────────────
create table if not exists eventos (
  id_evento    bigint primary key generated by default as identity,
  tipo         text check (tipo in ('Subasta','Exposición')),
  modalidad    text check (modalidad in ('Presencial','Virtual','Híbrido','En línea')),
  titulo       text   not null,
  fecha        date   not null,
  fecha_corta  jsonb,                        -- { "dia":"28","mes":"Jul" }
  lugar        text,
  imagen       text,
  descripcion  text,
  href         text,
  fichas_ids   jsonb                         -- [9,10] IDs de obras participantes
);

alter table eventos enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='eventos' and policyname='Lectura pública de eventos') then
    execute 'create policy "Lectura pública de eventos" on eventos for select using (true)';
  end if;
end $$;


-- ── Productos Cocina ──────────────────────────────────────────
create table if not exists productos_cocina (
  id              bigint primary key generated by default as identity,
  nombre          text    not null,
  productor       text    not null,
  origen          text    not null,
  descripcion     text    not null,
  imagen          text    not null,
  precio          numeric(10,2) not null,
  unidad          text    not null,
  categoria       text    not null
                    check (categoria in ('Vinos','Aceites','Especias','Chocolates','Conservas','Mieles')),
  destacado       boolean default false,
  activo          boolean default true,
  productor_email text                       -- FK lógico → accesos_prueba.email del productor
);

alter table productos_cocina enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='productos_cocina' and policyname='Lectura pública de productos cocina') then
    execute 'create policy "Lectura pública de productos cocina" on productos_cocina for select using (true)';
  end if;
end $$;

create index if not exists idx_cocina_categoria  on productos_cocina(categoria);
create index if not exists idx_cocina_productor  on productos_cocina(productor);
create index if not exists idx_cocina_activo     on productos_cocina(activo);


-- ════════════════════════════════════════════════════════════
--  AUTH Y PERFILES
-- ════════════════════════════════════════════════════════════

-- ── Usuarios (auth custom sin Supabase Auth) ──────────────────
--    Artistas y empresas aprobados vía solicitudes.
--    Compradores se registran directo.
--    Productores asignados manualmente.
create table if not exists usuarios (
  email        text primary key,
  clave        text not null,               -- ⚠ texto plano — pendiente bcrypt
  rol          text not null
                 check (rol in ('artista','comprador','empresa','productor','admin')),
  nombre       text    default '',
  bio          text    default '',
  especialidad text    default '',
  pais         text    default '',
  slug         text    unique,              -- solo empresas: "mi-galeria"
  avatar_url   text    default '',
  banner_url   text    default '',
  created_at   timestamptz default now()
);

alter table usuarios enable row level security;
do $$ begin
  -- Lectura pública: login desde el cliente usa anon key
  if not exists (select 1 from pg_policies where tablename='usuarios' and policyname='Lectura pública de usuarios') then
    execute 'create policy "Lectura pública de usuarios" on usuarios for select using (true)';
  end if;
  -- Inserción pública: registro de compradores
  if not exists (select 1 from pg_policies where tablename='usuarios' and policyname='Inserción pública de usuarios') then
    execute 'create policy "Inserción pública de usuarios" on usuarios for insert with check (true)';
  end if;
end $$;


-- ── Perfiles (Supabase Auth) ──────────────────────────────────
--    Ligados a auth.users. Artistas/empresas/compradores/productores
--    con cuenta GoTrue también tienen fila aquí.
create table if not exists perfiles (
  id           uuid references auth.users(id) on delete cascade primary key,
  rol          text not null
                 check (rol in ('artista','comprador','empresa','admin','productor')),
  nombre       text    default '',
  bio          text    default '',
  especialidad text    default '',
  pais         text    default '',
  slug         text    unique,
  avatar_url   text    default '',
  banner_url   text    default '',          -- portada/banner del perfil
  creado_at    timestamptz default now()
);

alter table perfiles enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='perfiles' and policyname='Ver propio perfil') then
    execute 'create policy "Ver propio perfil" on perfiles for select using (auth.uid() = id)';
  end if;
  if not exists (select 1 from pg_policies where tablename='perfiles' and policyname='Crear propio perfil') then
    execute 'create policy "Crear propio perfil" on perfiles for insert with check (auth.uid() = id)';
  end if;
  if not exists (select 1 from pg_policies where tablename='perfiles' and policyname='Editar propio perfil') then
    execute 'create policy "Editar propio perfil" on perfiles for update using (auth.uid() = id)';
  end if;
end $$;


-- ── Solicitudes de acceso ─────────────────────────────────────
--    Artistas y empresas que solicitan unirse.
--    El admin las aprueba → se mueven a usuarios.
create table if not exists solicitudes (
  id           bigint primary key generated always as identity,
  email        text   not null,
  clave        text   not null,
  rol          text   not null check (rol in ('artista','empresa')),
  nombre       text   default '',
  bio          text   default '',
  especialidad text   default '',
  pais         text   default '',
  motivacion   text   default '',
  estado       text   default 'pendiente'
                 check (estado in ('pendiente','aprobado','rechazado')),
  motivo       text,                        -- motivo de rechazo escrito por admin (nullable)
  revisado_at  timestamptz,
  created_at   timestamptz default now()
);

alter table solicitudes enable row level security;
do $$ begin
  -- Cualquiera puede crear una solicitud
  if not exists (select 1 from pg_policies where tablename='solicitudes' and policyname='Inserción pública de solicitudes') then
    execute 'create policy "Inserción pública de solicitudes" on solicitudes for insert with check (true)';
  end if;
  -- Lectura solo vía service role (admin panel usa getServerSupabase())
end $$;

-- Realtime habilitado para solicitudes (el admin recibe notificaciones en vivo)
-- Activar desde Supabase Dashboard → Database → Replication → solicitudes


-- ── Cuentas de prueba (test / localhost) ─────────────────────
--    Solo para desarrollo. No usar en producción.
create table if not exists accesos_prueba (
  email      text primary key,
  clave      text not null,
  rol        text not null
               check (rol in ('artista','comprador','empresa','productor','admin')),
  nombre     text default '',
  created_at timestamptz default now()
);

alter table accesos_prueba enable row level security;
do $$ begin
  -- Lectura pública: el cliente verifica credenciales con anon key
  if not exists (select 1 from pg_policies where tablename='accesos_prueba' and policyname='Lectura pública accesos_prueba') then
    execute 'create policy "Lectura pública accesos_prueba" on accesos_prueba for select using (true)';
  end if;
end $$;


-- ════════════════════════════════════════════════════════════
--  TRANSACCIONES
-- ════════════════════════════════════════════════════════════

-- ── Ventas (Mercado Pago) ─────────────────────────────────────
create table if not exists ventas (
  id                  bigint primary key generated always as identity,
  obra_id             bigint references obras(id_obra) on delete set null,
  titulo              text,
  precio              numeric(10,2),
  tipo                text,
  comprador_nombre    text,
  comprador_email     text,
  comprador_telefono  text,
  mensaje             text,
  mp_preference_id    text,                -- ID de preferencia Mercado Pago
  mp_payment_id       text,                -- ID de pago (llega por webhook)
  estado              text default 'pendiente'
                        check (estado in ('pendiente','en_proceso','pagado','cancelado')),
  created_at          timestamptz default now()
);

-- Acceso solo vía service role (webhook + admin)


-- ── Reseñas ───────────────────────────────────────────────────
create table if not exists resenas (
  id         bigint primary key generated always as identity,
  obra_id    bigint references obras(id_obra) on delete cascade,
  nombre     text   not null,
  estrellas  int    not null check (estrellas between 1 and 5),
  comentario text   not null,
  email      text,                          -- nullable; usado para anti-duplicado
  created_at timestamptz default now(),
  unique (obra_id, email)                   -- un email = una reseña por obra
);

alter table resenas enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='resenas' and policyname='Lectura pública de reseñas') then
    execute 'create policy "Lectura pública de reseñas" on resenas for select using (true)';
  end if;
  if not exists (select 1 from pg_policies where tablename='resenas' and policyname='Inserción pública de reseñas') then
    execute 'create policy "Inserción pública de reseñas" on resenas for insert with check (true)';
  end if;
end $$;


-- ════════════════════════════════════════════════════════════
--  CAPTURAS DE DATOS (formularios públicos)
-- ════════════════════════════════════════════════════════════

-- ── Newsletter ────────────────────────────────────────────────
create table if not exists suscriptores (
  id         bigint primary key generated always as identity,
  email      text   unique not null,
  created_at timestamptz default now()
);


-- ── Contacto ──────────────────────────────────────────────────
create table if not exists contactos (
  id         bigint primary key generated always as identity,
  nombre     text,
  email      text,
  asunto     text,
  mensaje    text,
  created_at timestamptz default now()
);


-- ── Registros a eventos ───────────────────────────────────────
create table if not exists registros_eventos (
  id         bigint primary key generated always as identity,
  evento_id  bigint references eventos(id_evento) on delete cascade,
  nombre     text   not null,
  email      text   not null,
  telefono   text,
  created_at timestamptz default now()
);


-- ════════════════════════════════════════════════════════════
--  FUNCIONES / RPCs
-- ════════════════════════════════════════════════════════════

-- ── Incrementar vistas de una obra (atómico) ─────────────────
create or replace function incrementar_vistas(obra_id bigint)
returns void
language sql
security definer
as $$
  update obras set vistas = vistas + 1 where id_obra = obra_id;
$$;


-- ════════════════════════════════════════════════════════════
--  ÍNDICES
-- ════════════════════════════════════════════════════════════

create index if not exists idx_obras_artista      on obras(id_artista);
create index if not exists idx_obras_movimiento   on obras(movimiento);
create index if not exists idx_obras_tamano       on obras(tamano);
create index if not exists idx_obras_color        on obras(color);
create index if not exists idx_obras_tipo         on obras(tipo);
create index if not exists idx_obras_estado       on obras(estado);
create index if not exists idx_obras_artista_email on obras(artista_email);
create index if not exists idx_obras_empresa_email on obras(empresa_email);
create index if not exists idx_solicitudes_estado on solicitudes(estado);
create index if not exists idx_ventas_estado      on ventas(estado);
create index if not exists idx_resenas_obra       on resenas(obra_id);
create index if not exists idx_registros_evento   on registros_eventos(evento_id);


-- ════════════════════════════════════════════════════════════
--  STORAGE (referencia — configurar desde el dashboard)
-- ════════════════════════════════════════════════════════════
--
--  Bucket "obras" (público):
--    obras/{id_obra}/principal.webp
--    obras/{id_obra}/{perspectiva}.webp
--    obras/cocina/{id_producto}.webp
--
--  Bucket "perfiles" (público):
--    {email_o_slug}/avatar.webp
--    {email_o_slug}/banner.webp
--
--  Políticas de Storage:
--    SELECT público en ambos buckets
--    INSERT autenticado (o service role para uploads vía /api/perfil/imagen)
