-- ============================================================
--  ERUDITO Galery — Datos iniciales (seeds)
--  Ejecutar DESPUÉS de schema.sql
--  Idempotente: ON CONFLICT DO NOTHING en todas las tablas
-- ============================================================

-- ── Migración de tablas existentes ──────────────────────────
-- Garantizar columnas identity por defecto (tablas creadas con GENERATED ALWAYS)
alter table artistas alter column id_artista set generated by default;
alter table obras    alter column id_obra     set generated by default;
alter table eventos  alter column id_evento   set generated by default;

-- artistas: email nullable (marcas/artistas históricos sin email)
alter table artistas alter column email drop not null;

-- obras: columnas añadidas en el esquema nuevo
alter table obras add column if not exists tipo            text;
alter table obras add column if not exists estrellas       int default 5;
alter table obras add column if not exists grafica_valor   jsonb;
alter table obras add column if not exists grafica_interes jsonb;
alter table obras add column if not exists certificaciones jsonb;

-- eventos: columnas añadidas en el esquema nuevo
alter table eventos add column if not exists fecha_corta jsonb;
alter table eventos add column if not exists href        text;
alter table eventos add column if not exists fichas_ids  jsonb;

-- perfiles: columna avatar_url añadida en el esquema nuevo
alter table public.perfiles add column if not exists avatar_url text default '';

-- eventos.modalidad: asegurar que 'En línea' esté permitido
alter table eventos drop constraint if exists eventos_modalidad_check;
alter table eventos add constraint eventos_modalidad_check
  check (modalidad in ('Presencial','Virtual','Híbrido','En línea'));

-- perfiles.rol: ampliar constraint para incluir el rol 'admin'
alter table public.perfiles drop constraint if exists perfiles_rol_check;
alter table public.perfiles add constraint perfiles_rol_check
  check (rol in ('artista', 'comprador', 'empresa', 'admin'));


-- ── Artistas (13) ────────────────────────────────────────────
insert into artistas (id_artista, nombre, vida, origen, especialidad, foto_perfil, biografia)
values
  (5,  'Merck Rathke',
       '1890 – 1960', 'Alemania', 'Expresionismo',
       'https://picsum.photos/seed/artista-5/400/400',
       'Pintor expresionista de origen alemán reconocido por su tratamiento singular de la figura humana: siluetas alargadas y estilizadas que capturan la tensión social y el misterio de la vida urbana. Su paleta cálida de ocres, rosas y negros profundos define un universo visual inconfundible en el que personajes enigmáticos coexisten entre lo real y lo onírico.'),

  (6,  'Ideas Creativas',
       '2020 – presente', 'Arte Digital', 'Arte Digital',
       'https://picsum.photos/seed/artista-6/400/400',
       'Estudio de arte digital especializado en ilustraciones hiperrealistas de la naturaleza. Sus obras combinan fotografía de alta precisión con técnicas de pintura digital para capturar la vitalidad y el color de la fauna silvestre, creando piezas decorativas de gran impacto visual.'),

  (7,  'Revolution Canvas',
       '2018 – presente', 'Arte Digital', 'Arte Digital',
       'https://picsum.photos/seed/artista-7/400/400',
       'Colectivo de arte digital que reinterpreta obras maestras del arte clásico con una estética urbana y de vanguardia. Sus piezas fusionan la monumentalidad de los grandes maestros con salpicaduras de color, grafiti y abstracción cromática, creando un diálogo vibrante entre el pasado y el presente.'),

  (8,  'Atelier Geométrico',
       '2015 – presente', 'Diseño Contemporáneo', 'Escultura Low-Poly',
       'https://picsum.photos/seed/artista-8/400/400',
       'Estudio de diseño especializado en esculturas decorativas de geometría low-poly. Sus piezas traducen la elegancia de la naturaleza — fauna, flora, figuras humanas — en formas facetadas de alta precisión, trabajadas en resina de alta densidad con acabados metálicos lujosos. Cada colección es una edición limitada pensada para espacios de diseño de autor.'),

  (9,  'Arte & Memorias',
       '2018 – presente', 'Arte Relacional', 'Arte Relacional',
       'https://picsum.photos/seed/artista-9/400/400',
       'Estudio dedicado al arte participativo y de memoria colectiva. Sus piezas — árboles de huellas, mapas de firmas, lienzos de votos — se conciben vacías y se completan con la presencia de cada invitado, convirtiendo cada evento en una obra única e irrepetible. El resultado es un objeto que contiene la huella literal de quienes estuvieron ahí.'),

  (10, 'HAUCOZE',
       '2016 – presente', 'Escultura Contemporánea', 'Escultura Figurativa',
       'https://picsum.photos/seed/artista-10/400/400',
       'Estudio de escultura figurativa especializado en colecciones de resina de alta densidad con acabados metálicos. Sus series capturan la energía del movimiento humano — músicos, deportistas, figuras urbanas — en piezas de detalle milimétrico pensadas para espacios de diseño contemporáneo. Cada figura es un instante congelado en actitud máxima.'),

  (11, 'UTTCMK',
       '2019 – presente', 'Escultura Abstracta', 'Escultura Abstracta',
       'https://picsum.photos/seed/artista-11/400/400',
       'Estudio de escultura abstracta especializado en figuras humanas de línea fluida con acabados en arenisca y resina natural. Sus piezas capturan estados contemplativos — el pensamiento, la lectura, la meditación — en formas orgánicas depuradas de todo detalle superfluo, pensadas para enriquecer espacios de trabajo, biblioteca y diseño nórdico.'),

  (12, 'GMMH',
       '2017 – presente', 'Escultura Expresionista', 'Escultura Expresionista',
       'https://picsum.photos/seed/artista-12/400/400',
       'Estudio especializado en esculturas de rostros abstractos con acabados en resina patinada. Sus colecciones exploran las emociones humanas fundamentales — el silencio, la introspección, la escucha — a través de formas expresionistas que fusionan textura orgánica con plata antigüa. Cada pieza es un estudio del gesto y la presencia, pensada para espacios de diseño intelectual.'),

  (13, 'Pop Maze Art',
       '2019 – presente', 'Arte Digital', 'Pop Art / WPAP',
       'https://picsum.photos/seed/artista-13/400/400',
       'Estudio de impresión artística especializado en el estilo WPAP (Wedha''s Pop Art Portrait): retratos fragmentados en planos de color plano y bordes nítidos que transforman figuras icónicas de la cultura pop en composiciones geométricas de alta energía. Sus prints en canvas de alta resolución están pensados para espacios jóvenes, estudios creativos y colecciones de cultura pop contemporánea.'),

  (14, 'Carta Mundi',
       '2016 – presente', 'Cartografía Histórica', 'Cartografía Histórica',
       'https://picsum.photos/seed/artista-14/400/400',
       'Estudio editorial especializado en la reproducción de cartografía histórica de alta fidelidad. Sus prints recuperan mapas originales de los siglos XVII al XIX — John Senex, Mercator, Blaeu — e imprimen sus detalles caligráficos y notaciones geográficas sobre canvas con pátina de pergamino envejecido. Cada pieza es un documento visual de cómo la humanidad imaginó el mundo antes de los satélites.'),

  (15, 'BestAlice',
       '2020 – presente', 'Arte Decorativo', 'Escultura Decorativa',
       'https://picsum.photos/seed/artista-15/400/400',
       'Estudio de escultura decorativa especializado en árboles de la vida con hojas de acrílico translúcido. Cada pieza entrelaza ramas de alambre pintado a mano con hojas individuales en vidrio acrílico de color — un espectro que va del amarillo y naranja al rojo, violeta, azul y verde esmeralda. Sus esculturas capturan la abundancia cromática de la naturaleza en objetos de mesa pensados para escritorios, consolas y espacios de meditación.'),

  (16, 'Yihui Arts',
       '2010 – presente', 'Pintura Decorativa', 'Pintura Decorativa',
       'https://picsum.photos/seed/artista-16/400/400',
       'Estudio especializado en pintura sobre canvas pintada a mano con textura en relieve. Sus obras combinan fondos abstractos de capas superpuestas —azules, grises y verdes al óleo— con motivos centrales de gran impacto visual: árboles desnudos, paisajes serenos y composiciones contemplativos que aportan calma y profundidad a cualquier espacio. Cada pieza incorpora acentos de pigmento dorado o ámbar que añaden calidez al conjunto.'),

  (17, 'Suruim',
       '2018 – presente', 'Escultura Decorativa', 'Escultura Decorativa',
       'https://picsum.photos/seed/artista-17/400/400',
       'Estudio de escultura decorativa especializado en figuras de animales con personalidad urbana. Sus piezas transforman arquetipos de la fauna — bulldogs, osos, conejos — en personajes dandis vestidos con trajes, pajaritas doradas y accesorios removibles. La resina de alta densidad con acabados mate y detalles en metal dorado convierte cada figura en un objeto de colección funcional: charola de escritorio, hucha o elemento escultórico de diseño.')

on conflict (id_artista) do nothing;

-- Reiniciar secuencia para que los próximos artistas auto-generados no colisionen
select setval('artistas_id_artista_seq', (select max(id_artista) from artistas));


-- ── Obras / Fichas (15) ──────────────────────────────────────
insert into obras (
  id_obra, id_artista, titulo, anio, descripcion, precio, tipo, tamano, color,
  movimiento, tecnica, estrellas, imagen_principal, perspectivas,
  grafica_valor, grafica_interes, certificaciones
)
values

  /* 9 — Underground Fantasy — Merck Rathke (5) */
  (9, 5, 'Underground Fantasy', 'c. 1925',
   'Una escena de misterio urbano: figuras estilizadas deambulan entre columnas y palmeras esquemáticas bajo una atmósfera cargada de tensión social. El hombre de negro que despliega un objeto ante las miradas inexpresivas de las mujeres crea una coreografía silenciosa entre lo mundano y lo fantástico.',
   54500, 'Impresión Oficial', 'Grande', 'Cálido', 'Expresionismo', 'Óleo', 5,
   '/obras/merck-rathke/principal.jpg',
   '["/obras/merck-rathke/principal.jpg","/obras/merck-rathke/sala-oscura.jpg","/obras/merck-rathke/sala-clara.jpg","/obras/merck-rathke/dormitorio.jpg"]',
   '[{"mes":"Ene","valor":36000},{"mes":"Feb","valor":37500},{"mes":"Mar","valor":37000},{"mes":"Abr","valor":40000},{"mes":"May","valor":43000},{"mes":"Jun","valor":47000},{"mes":"Jul","valor":46000},{"mes":"Ago","valor":49000},{"mes":"Sep","valor":51000},{"mes":"Oct","valor":52500},{"mes":"Nov","valor":54000},{"mes":"Dic","valor":54500}]',
   '[42,58,35,75,60,70,65]',
   '["Verificada por ERUDITO Galery","Impresión Oficial con sello de autenticidad","Activo Financiero Clase B"]'),

  /* 10 — Colibrí en Flor — Ideas Creativas (6) */
  (10, 6, 'Colibrí en Flor', '2024',
   'Un colibrí de plumaje turquesa suspendido en pleno vuelo ante una explosión de flores tropicales rojas y naranjas. La técnica digital hiperrealista captura cada detalle del ave — la iridiscencia de sus plumas, el movimiento congelado de sus alas — sobre un fondo oscuro que intensifica la luminosidad del conjunto.',
   37500, 'Impresión Oficial', 'Grande', 'Frío', 'Arte Digital', 'Digital', 5,
   '/obras/colibri-digital/principal.jpg',
   '["/obras/colibri-digital/principal.jpg","/obras/colibri-digital/sala-moderna.jpg","/obras/colibri-digital/comedor.jpg","/obras/colibri-digital/oficina.jpg"]',
   '[{"mes":"Ene","valor":24000},{"mes":"Feb","valor":25000},{"mes":"Mar","valor":26500},{"mes":"Abr","valor":27500},{"mes":"May","valor":30000},{"mes":"Jun","valor":32500},{"mes":"Jul","valor":32000},{"mes":"Ago","valor":34000},{"mes":"Sep","valor":35000},{"mes":"Oct","valor":36000},{"mes":"Nov","valor":37000},{"mes":"Dic","valor":37500}]',
   '[55,72,48,88,70,82,78]',
   '["Verificada por ERUDITO Galery","Impresión Oficial con sello de autenticidad","Certificado de edición limitada"]'),

  /* 11 — La Creación — Pop Art — Revolution Canvas (7) */
  (11, 7, 'La Creación — Pop Art', '2022',
   'Reinterpretación contemporánea de La Creación de Adán de Miguel Ángel. Las manos icónicas que casi se tocan emergen en blanco y negro de un estallido de pigmentos: amarillos, azules, violetas y rojos que transforman la escena sagrada en una declaración de arte urbano y vanguardia cromática.',
   28000, 'Impresión Oficial', 'Grande', 'Frío', 'Arte Digital', 'Digital', 5,
   '/obras/revolution-canvas/principal.jpg',
   '["/obras/revolution-canvas/principal.jpg","/obras/revolution-canvas/sala-gris.jpg","/obras/revolution-canvas/loft.jpg"]',
   '[{"mes":"Ene","valor":18000},{"mes":"Feb","valor":19000},{"mes":"Mar","valor":18500},{"mes":"Abr","valor":20000},{"mes":"May","valor":22000},{"mes":"Jun","valor":24000},{"mes":"Jul","valor":23500},{"mes":"Ago","valor":25000},{"mes":"Sep","valor":26000},{"mes":"Oct","valor":26500},{"mes":"Nov","valor":27000},{"mes":"Dic","valor":28000}]',
   '[62,78,55,90,74,85,80]',
   '["Verificada por ERUDITO Galery","Impresión Oficial con sello de autenticidad","Edición limitada numerada"]'),

  /* 12 — Noche Estrellada sobre Bellas Artes — Revolution Canvas (7) */
  (12, 7, 'Noche Estrellada sobre Bellas Artes', '2024',
   'Fusión magistral entre la pincelada giratoria de Van Gogh y la majestuosidad neoclásica del Palacio de Bellas Artes de la Ciudad de México. El cielo azul turquesa con sus remolinos y astros dorados envuelve la cúpula iluminada del palacio, creando un diálogo poético entre el expresionismo europeo y el patrimonio cultural mexicano.',
   31500, 'Impresión Oficial', 'Grande', 'Frío', 'Arte Digital', 'Digital', 5,
   '/obras/bellas-artes-noche/principal.jpg',
   '["/obras/bellas-artes-noche/principal.jpg","/obras/bellas-artes-noche/sala-moderna.jpg","/obras/bellas-artes-noche/comedor.jpg"]',
   '[{"mes":"Ene","valor":20000},{"mes":"Feb","valor":21000},{"mes":"Mar","valor":20500},{"mes":"Abr","valor":22500},{"mes":"May","valor":24500},{"mes":"Jun","valor":26500},{"mes":"Jul","valor":26000},{"mes":"Ago","valor":27500},{"mes":"Sep","valor":28500},{"mes":"Oct","valor":29500},{"mes":"Nov","valor":30500},{"mes":"Dic","valor":31500}]',
   '[68,82,58,95,78,90,86]',
   '["Verificada por ERUDITO Galery","Impresión Oficial con sello de autenticidad","Edición limitada numerada","Homenaje al Patrimonio Cultural Mexicano"]'),

  /* 13 — El Ángel — Paseo de la Reforma — Revolution Canvas (7) */
  (13, 7, 'El Ángel — Paseo de la Reforma', '2024',
   'La Columna de la Independencia emerge como eje central de una composición explosiva: rascacielos de teal y magenta flanquean el Paseo de la Reforma mientras la calzada se convierte en un espejo de naranjas, rojos y ocres bajo la lluvia. La pincelada de cuchillo imprime volumen y urgencia a uno de los iconos más reconocibles de la Ciudad de México.',
   29500, 'Impresión Oficial', 'Grande', 'Cálido', 'Arte Digital', 'Digital', 5,
   '/obras/angel-reforma/principal.jpg',
   '["/obras/angel-reforma/principal.jpg","/obras/angel-reforma/sala-calida.jpg","/obras/angel-reforma/sala-moderna.jpg"]',
   '[{"mes":"Ene","valor":18500},{"mes":"Feb","valor":19500},{"mes":"Mar","valor":19000},{"mes":"Abr","valor":21000},{"mes":"May","valor":23000},{"mes":"Jun","valor":25000},{"mes":"Jul","valor":24500},{"mes":"Ago","valor":26000},{"mes":"Sep","valor":27000},{"mes":"Oct","valor":27500},{"mes":"Nov","valor":28500},{"mes":"Dic","valor":29500}]',
   '[70,85,60,97,80,92,88]',
   '["Verificada por ERUDITO Galery","Impresión Oficial con sello de autenticidad","Edición limitada numerada","Homenaje al Patrimonio Cultural Mexicano"]'),

  /* 14 — Dúo Venado Dorado — Atelier Geométrico (8) */
  (14, 8, 'Dúo Venado Dorado', '2021',
   'Par de ciervos en geometría low-poly: uno recostado en actitud contemplativa, el otro erguido con la cornamenta alzada. El acabado en resina dorada mate convierte cada faceta en un plano de luz distinto según el ángulo de visión. Dos piezas que dialogan entre el reposo y la vigilancia, pensadas para repisas, consolas y mesas de diseño de autor.',
   12500, 'Físico', 'Pequeño', 'Cálido', 'Minimalismo', 'Escultura', 4,
   '/obras/venado-dorado/principal.jpg',
   '["/obras/venado-dorado/principal.jpg","/obras/venado-dorado/fondo-blanco.jpg","/obras/venado-dorado/mesa-sala.jpg","/obras/venado-dorado/detalle.jpg"]',
   '[{"mes":"Ene","valor":8500},{"mes":"Feb","valor":8800},{"mes":"Mar","valor":8700},{"mes":"Abr","valor":9200},{"mes":"May","valor":10000},{"mes":"Jun","valor":10800},{"mes":"Jul","valor":10500},{"mes":"Ago","valor":11200},{"mes":"Sep","valor":11500},{"mes":"Oct","valor":11800},{"mes":"Nov","valor":12200},{"mes":"Dic","valor":12500}]',
   '[48,65,40,82,65,76,72]',
   '["Verificada por ERUDITO Galery","Edición limitada de coleccionista","Resina de alta densidad con acabado dorado"]'),

  /* 15 — Árbol de Huellas — Amor y Unión — Arte & Memorias (9) */
  (15, 9, 'Árbol de Huellas — Amor y Unión', '2023',
   'Lienzo participativo en forma de árbol con corazón entrelazado y dos pájaros. Las ramas llegan vacías al evento — son los invitados quienes, con su huella dactilar entintada, crean cada hoja de color. Al final de la celebración la obra es única e irrepetible: un retrato literal de todos los que estuvieron presentes.',
   7500, 'Físico', 'Mediano', 'Neutro', 'Arte Relacional', 'Mixta', 5,
   '/obras/arbol-huellas/principal.jpg',
   '["/obras/arbol-huellas/principal.jpg","/obras/arbol-huellas/sala-nordica.jpg","/obras/arbol-huellas/sala-cojines.jpg","/obras/arbol-huellas/plantilla.jpg"]',
   '[{"mes":"Ene","valor":5000},{"mes":"Feb","valor":5200},{"mes":"Mar","valor":5100},{"mes":"Abr","valor":5500},{"mes":"May","valor":6000},{"mes":"Jun","valor":6500},{"mes":"Jul","valor":6300},{"mes":"Ago","valor":6700},{"mes":"Sep","valor":7000},{"mes":"Oct","valor":7100},{"mes":"Nov","valor":7300},{"mes":"Dic","valor":7500}]',
   '[72,88,65,98,82,94,90]',
   '["Verificada por ERUDITO Galery","Pieza única — completada por los invitados","Incluye almohadillas de tinta de colores","Certificado de evento con fecha y lugar"]'),

  /* 16 — La Banda de Rock — HAUCOZE (10) */
  (16, 10, 'La Banda de Rock', '2021',
   'Colección de cuatro figuras en resina: guitarrista inclinado en riff extremo, baterista con el brazo en alto, vocalista con el micrófono al límite y tecladista en plena entrega. El acabado grafito mate con detalles en plata captura la energía en vivo de una banda en su momento culmen. Piezas de colección para amantes de la música y el diseño de interiores.',
   18500, 'Físico', 'Pequeño', 'Neutro', 'Figurativismo', 'Escultura', 5,
   '/obras/banda-rock-haucoze/principal.jpg',
   '["/obras/banda-rock-haucoze/principal.jpg","/obras/banda-rock-haucoze/marmol.jpg","/obras/banda-rock-haucoze/detalle.jpg","/obras/banda-rock-haucoze/multivista.jpg"]',
   '[{"mes":"Ene","valor":12000},{"mes":"Feb","valor":12500},{"mes":"Mar","valor":12200},{"mes":"Abr","valor":13500},{"mes":"May","valor":14800},{"mes":"Jun","valor":16000},{"mes":"Jul","valor":15500},{"mes":"Ago","valor":16800},{"mes":"Sep","valor":17200},{"mes":"Oct","valor":17500},{"mes":"Nov","valor":18000},{"mes":"Dic","valor":18500}]',
   '[65,80,55,92,75,88,84]',
   '["Verificada por ERUDITO Galery","Colección oficial HAUCOZE","Resina de alta densidad con acabado metálico","Edición limitada de coleccionista"]'),

  /* 17 — El Lector — UTTCMK (11) */
  (17, 11, 'El Lector', '2022',
   'Figura humana sin rostro sentada en posición de loto con un libro abierto entre las manos y la palma apoyada en la sien. La superficie en arenisca beige mate de resina elimina todo detalle anatómico para concentrar la atención en la postura: la curvatura de la espalda, la tensión de los dedos y la inclinación de la cabeza narran la inmersión total en la lectura.',
   9500, 'Físico', 'Pequeño', 'Neutro', 'Abstracto', 'Escultura', 5,
   '/obras/el-lector-uttcmk/principal.jpg',
   '["/obras/el-lector-uttcmk/principal.jpg","/obras/el-lector-uttcmk/biblioteca.jpg","/obras/el-lector-uttcmk/escritorio.jpg","/obras/el-lector-uttcmk/producto.jpg"]',
   '[{"mes":"Ene","valor":6000},{"mes":"Feb","valor":6300},{"mes":"Mar","valor":6200},{"mes":"Abr","valor":6800},{"mes":"May","valor":7400},{"mes":"Jun","valor":8000},{"mes":"Jul","valor":7800},{"mes":"Ago","valor":8300},{"mes":"Sep","valor":8600},{"mes":"Oct","valor":8800},{"mes":"Nov","valor":9200},{"mes":"Dic","valor":9500}]',
   '[58,74,50,88,72,84,80]',
   '["Verificada por ERUDITO Galery","Colección oficial UTTCMK","Resina con acabado arenisca natural","Edición limitada de coleccionista"]'),

  /* 18 — El Trío del Silencio — GMMH (12) */
  (18, 12, 'El Trío del Silencio', '2023',
   'Tres rostros abstractos en resina plata antigüa interpretan la trilogía milenaria: Ver, Oír, Callar. La textura cincelada a mano y el acabado plateado envejecido convierten cada figura en una meditación sobre los sentidos. Bases en madera negra que anclan la composición con sobriedad. Un ensemble filosófico para biblioteca, escritorio o consola de diseño.',
   8900, 'Físico', 'Pequeño', 'Neutro', 'Expresionismo', 'Escultura', 5,
   '/obras/silencio-trio/principal.jpg',
   '["/obras/silencio-trio/principal.jpg","/obras/silencio-trio/fondo-blanco.jpg","/obras/silencio-trio/mesa-rustica.jpg","/obras/silencio-trio/repisa.jpg"]',
   '[{"mes":"Ene","valor":5500},{"mes":"Feb","valor":5800},{"mes":"Mar","valor":5700},{"mes":"Abr","valor":6200},{"mes":"May","valor":6800},{"mes":"Jun","valor":7400},{"mes":"Jul","valor":7200},{"mes":"Ago","valor":7700},{"mes":"Sep","valor":8000},{"mes":"Oct","valor":8300},{"mes":"Nov","valor":8600},{"mes":"Dic","valor":8900}]',
   '[60,76,52,90,74,86,82]',
   '["Verificada por ERUDITO Galery","Colección oficial GMMH","Resina con acabado plata antigüa patinada","Edición limitada de coleccionista"]'),

  /* 19 — El Sombrero de Paja — WPAP — Pop Maze Art (13) */
  (19, 13, 'El Sombrero de Paja — WPAP', '2022',
   'Retrato en técnica WPAP (Wedha''s Pop Art Portrait) de uno de los personajes más icónicos del anime contemporáneo: el joven capitán de sombrero de paja. La composición fragmenta el rostro en planos geométricos de colores saturados — amarillos, naranjas, verdes, magenta — sobre un fondo azul marino profundo. Una declaración de cultura pop que transforma la animación en arte de coleccionista.',
   2800, 'Impresión Oficial', 'Grande', 'Frío', 'Pop Art', 'Digital', 5,
   '/obras/sombrero-paja-wpap/principal.jpg',
   '["/obras/sombrero-paja-wpap/principal.jpg","/obras/sombrero-paja-wpap/estudio-rustico.jpg","/obras/sombrero-paja-wpap/sala-libros.jpg"]',
   '[{"mes":"Ene","valor":1800},{"mes":"Feb","valor":1900},{"mes":"Mar","valor":1850},{"mes":"Abr","valor":2000},{"mes":"May","valor":2200},{"mes":"Jun","valor":2400},{"mes":"Jul","valor":2350},{"mes":"Ago","valor":2500},{"mes":"Sep","valor":2600},{"mes":"Oct","valor":2650},{"mes":"Nov","valor":2750},{"mes":"Dic","valor":2800}]',
   '[75,90,68,98,85,96,92]',
   '["Verificada por ERUDITO Galery","Impresión en canvas de alta resolución","Edición limitada numerada"]'),

  /* 20 — Mappa Mundi — Carta Mundi (14) */
  (20, 14, 'Mappa Mundi — Carta de los Dos Hemisferios', 'c. 1721 (reproducción)',
   'Reproducción en alta fidelidad del mapa mundial de John Senex, cartógrafo real inglés. Los dos hemisferios en proyección esférica, la caligrafía tipográfica del siglo XVIII y las manchas de envejecimiento del pergamino recrean el asombro geográfico de una época en que el mundo aún guardaba bordes inciertos.',
   2500, 'Impresión Oficial', 'Grande', 'Cálido', 'Cartografía Histórica', 'Digital', 5,
   '/obras/mappa-mundi/principal.jpg',
   '["/obras/mappa-mundi/principal.jpg","/obras/mappa-mundi/comedor.jpg","/obras/mappa-mundi/sala.jpg"]',
   '[{"mes":"Ene","valor":1600},{"mes":"Feb","valor":1700},{"mes":"Mar","valor":1650},{"mes":"Abr","valor":1800},{"mes":"May","valor":2000},{"mes":"Jun","valor":2100},{"mes":"Jul","valor":2050},{"mes":"Ago","valor":2200},{"mes":"Sep","valor":2300},{"mes":"Oct","valor":2350},{"mes":"Nov","valor":2450},{"mes":"Dic","valor":2500}]',
   '[70,84,62,94,78,90,86]',
   '["Verificada por ERUDITO Galery","Reproducción de alta fidelidad sobre canvas","Basada en cartografía original John Senex (c. 1721)","Impresión con tinta resistente a los rayos UV"]'),

  /* 21 — Árbol de la Vida — Hojas de Cristal — BestAlice (15) */
  (21, 15, 'Árbol de la Vida — Hojas de Cristal', '2023',
   'Escultura de mesa que reinterpreta el arquetipo universal del árbol de la vida: ramas de alambre de cobre pintado sostienen más de cien hojas individuales de acrílico translúcido en un espectro completo de color — del amarillo solar al naranja otoñal, el rojo intenso, el magenta, el azul zafiro y el verde esmeralda. La luz que atraviesa las hojas proyecta sombras cromáticas sobre la superficie, convirtiendo el entorno en parte de la obra.',
   4800, 'Físico', 'Pequeño', 'Cálido', 'Arte Decorativo', 'Mixta', 5,
   '/obras/arbol-vida-cristal/principal.jpg',
   '["/obras/arbol-vida-cristal/principal.jpg","/obras/arbol-vida-cristal/mesa-madera.jpg","/obras/arbol-vida-cristal/consola.jpg","/obras/arbol-vida-cristal/fondo-blanco.jpg"]',
   '[{"mes":"Ene","valor":3000},{"mes":"Feb","valor":3200},{"mes":"Mar","valor":3100},{"mes":"Abr","valor":3400},{"mes":"May","valor":3700},{"mes":"Jun","valor":4000},{"mes":"Jul","valor":3900},{"mes":"Ago","valor":4200},{"mes":"Sep","valor":4400},{"mes":"Oct","valor":4500},{"mes":"Nov","valor":4700},{"mes":"Dic","valor":4800}]',
   '[72,86,64,96,80,92,88]',
   '["Verificada por ERUDITO Galery","Colección oficial BestAlice","Hojas en acrílico translúcido de color","Estructura de alambre pintado a mano"]'),

  /* 22 — El Árbol Blanco — Calma Invernal — Yihui Arts (16) */
  (22, 16, 'El Árbol Blanco — Calma Invernal', '2023',
   'Pintura sobre canvas pintada a mano que representa un árbol desnudo de blanco puro sobre un fondo abstracto de capas al óleo en azul profundo, teal y gris perla. La ausencia de hojas no evoca pérdida sino quietud: el árbol en reposo antes del florecimiento. Detalles en pigmento dorado y ámbar en las raíces anclan la composición con un acento cálido que contrasta con la serenidad fría del cielo.',
   3500, 'Físico', 'Grande', 'Frío', 'Arte Decorativo', 'Óleo', 5,
   '/obras/arbol-blanco-yihui/principal.jpg',
   '["/obras/arbol-blanco-yihui/principal.jpg","/obras/arbol-blanco-yihui/detalle.jpg","/obras/arbol-blanco-yihui/sala-azul.jpg","/obras/arbol-blanco-yihui/sala-turquesa.jpg","/obras/arbol-blanco-yihui/sala-gris.jpg"]',
   '[{"mes":"Ene","valor":2200},{"mes":"Feb","valor":2300},{"mes":"Mar","valor":2250},{"mes":"Abr","valor":2500},{"mes":"May","valor":2700},{"mes":"Jun","valor":2900},{"mes":"Jul","valor":2850},{"mes":"Ago","valor":3000},{"mes":"Sep","valor":3150},{"mes":"Oct","valor":3250},{"mes":"Nov","valor":3400},{"mes":"Dic","valor":3500}]',
   '[68,82,60,94,78,90,86]',
   '["Verificada por ERUDITO Galery","Pintura original al óleo sobre canvas","Colección oficial Yihui Arts","Acentos en pigmento dorado aplicados a mano"]'),

  /* 23 — El Bulldog Dandy — Suruim (17) */
  (23, 17, 'El Bulldog Dandy', '2022',
   'Bulldog francés de resina mate vestido con traje de etiqueta, pajarita dorada y gafas de sol con lentes iridiscentes teal. La figura sostiene una charola circular en metal dorado diseñada para llaves, joyas, tarjetas o dulces — convirtiendo al personaje en un mayordomo de escritorio con actitud. Incluye ranura interior para monedas y gafas removibles. Disponible en gris topo y negro profundo.',
   3800, 'Físico', 'Pequeño', 'Neutro', 'Figurativismo', 'Escultura', 4,
   '/obras/bulldog-dandy/principal.jpg',
   '["/obras/bulldog-dandy/principal.jpg","/obras/bulldog-dandy/ambientes.jpg","/obras/bulldog-dandy/detalle.jpg"]',
   '[{"mes":"Ene","valor":2400},{"mes":"Feb","valor":2500},{"mes":"Mar","valor":2450},{"mes":"Abr","valor":2700},{"mes":"May","valor":2900},{"mes":"Jun","valor":3100},{"mes":"Jul","valor":3050},{"mes":"Ago","valor":3200},{"mes":"Sep","valor":3400},{"mes":"Oct","valor":3500},{"mes":"Nov","valor":3650},{"mes":"Dic","valor":3800}]',
   '[74,88,65,96,80,92,89]',
   '["Verificada por ERUDITO Galery","Colección oficial Suruim","Resina de alta densidad con acabado mate","Accesorios en metal dorado — gafas removibles"]')

on conflict (id_obra) do nothing;

-- Reiniciar secuencia
select setval('obras_id_obra_seq', (select max(id_obra) from obras));


-- ── Eventos (4) ──────────────────────────────────────────────
insert into eventos (id_evento, tipo, modalidad, titulo, fecha, fecha_corta, lugar, imagen, descripcion, href, fichas_ids)
values
  (1, 'Subasta', 'En línea',
   'Grandes Maestros: Expresionismo y Arte Digital',
   '2026-07-28',
   '{"dia":"28","mes":"Jul"}',
   'Subasta en línea — ERUDITO Galery',
   '/obras/merck-rathke/principal.jpg',
   'Lotes de alto valor: Underground Fantasy (Merck Rathke, $54,500 MXN) y Colibrí en Flor (Ideas Creativas, $37,500 MXN). Piezas con certificación y tasación incluida.',
   '/eventos/1',
   '[9,10]'),

  (2, 'Exposición', 'Presencial',
   'Revolution Canvas: La Ciudad Reimaginada',
   '2026-08-12',
   '{"dia":"12","mes":"Ago"}',
   'Galería ERUDITO — Ciudad de México',
   '/obras/bellas-artes-noche/principal.jpg',
   'Muestra completa del colectivo Revolution Canvas: Noche Estrellada sobre Bellas Artes, El Ángel y La Creación — Pop Art. Un recorrido por los íconos de la Ciudad de México reinterpretados en arte digital.',
   '/eventos/2',
   '[11,12,13]'),

  (3, 'Subasta', 'Presencial',
   'Colección Escultórica: Resina y Movimiento',
   '2026-08-22',
   '{"dia":"22","mes":"Ago"}',
   'Casa de Subastas ERUDITO — Guadalajara',
   '/obras/banda-rock-haucoze/principal.jpg',
   'Tres colecciones en un solo evento: La Banda de Rock (HAUCOZE), El Lector (UTTCMK) y El Trío del Silencio (GMMH). Escultura figurativa y expresionista en resina de alta densidad.',
   '/eventos/3',
   '[16,17,18]'),

  (4, 'Exposición', 'En línea',
   'Cultura Pop & Cartografía: Dos Mundos',
   '2026-07-20',
   '{"dia":"20","mes":"Jul"}',
   'Exposición digital — ERUDITO Galery',
   '/obras/sombrero-paja-wpap/principal.jpg',
   'Diálogo entre lo contemporáneo y lo histórico: El Sombrero de Paja WPAP (Pop Maze Art) frente a la Mappa Mundi de John Senex (Carta Mundi). Arte que cruza siglos y géneros.',
   '/eventos/4',
   '[19,20]')

on conflict (id_evento) do nothing;

-- Reiniciar secuencia
select setval('eventos_id_evento_seq', (select max(id_evento) from eventos));


-- ── Productos Cocina ────────────────────────────────────────
insert into public.productos_cocina
  (id, nombre, productor, origen, descripcion, imagen, precio, unidad, categoria, destacado, activo)
values
  -- Vinos
  (1,
   'Monte Xanic Gran Ricardo 2019',
   'Monte Xanic',
   'Valle de Guadalupe, Baja California',
   'Ensamble de Cabernet Sauvignon, Merlot y Petit Verdot de los mejores lotes de la bodega. Crianza de 18 meses en barricas nuevas de roble francés. Aromas de ciruela madura, grafito y tabaco, con un tanino sedoso y una larga persistencia. La referencia del vino de autor mexicano.',
   'https://picsum.photos/seed/vino-monte-xanic/600/800',
   890.00, '750 ml', 'Vinos', true, true),

  (2,
   'Casa Madero 3V Gran Reserva 2020',
   'Casa Madero',
   'Valle de Parras, Coahuila',
   'Ensamble de Cabernet Sauvignon, Merlot y Shiraz proveniente de la bodega más antigua de América (1597). Crianza de 14 meses en roble francés. Intenso, con notas de mora, pimienta negra y vainilla. Emblema del vino del norte de México.',
   'https://picsum.photos/seed/vino-casa-madero/600/800',
   620.00, '750 ml', 'Vinos', false, true),

  (3,
   'Riesling Spätlese Mosel 2021',
   'Dr. Loosen',
   'Mosela, Alemania',
   'Riesling de viñedos de pizarra azul con más de 60 años de edad. Cosecha tardía que equilibra una acidez eléctrica con una dulzura natural delicada. Notas de melocotón blanco, flores y mineralidad pétrea. Imprescindible para entender el Riesling en su máxima expresión.',
   'https://picsum.photos/seed/vino-dr-loosen/600/800',
   780.00, '750 ml', 'Vinos', false, true),

  -- Aceites
  (4,
   'Aceite de Oliva Hojiblanca EVOO',
   'Castillo de Canena',
   'Jaén, España',
   'Aceite de primera prensada en frío, cosecha temprana de aceitunas Hojiblanca. Índice de acidez inferior a 0.15%. Aroma fresco a hierba cortada y tomate verde, con un amargor elegante y picante limpio que evidencia un alto contenido de polifenoles.',
   'https://picsum.photos/seed/aceite-canena/600/800',
   420.00, '500 ml', 'Aceites', true, true),

  (5,
   'Aceite de Argán Gastronómico',
   'Amal Coopérative',
   'Souss-Massa, Marruecos',
   'Producido por la cooperativa femenina Amal mediante tostado artesanal y prensado en frío de las almendras del argán. Aroma intenso a fruto seco tostado, sabor profundo y persistente. Ideal para aderezar cuscús, ensaladas y postres tradicionales.',
   'https://picsum.photos/seed/aceite-argan/600/800',
   580.00, '250 ml', 'Aceites', false, true),

  (6,
   'Aceite de Aguacate Puro',
   'Chosen Foods',
   'Michoacán, México',
   'Prensado en frío de aguacates Hass de Michoacán en su punto óptimo de madurez. Punto de humo de 270 °C, ideal para altas temperaturas. Perfil suave con notas de mantequilla y hierba fresca. Certificado non-GMO y sin refinar.',
   'https://picsum.photos/seed/aceite-aguacate/600/800',
   310.00, '500 ml', 'Aceites', false, true),

  -- Especias
  (7,
   'Vainilla de Papantla Entera',
   'Gaya Vainilla',
   'Papantla, Veracruz, México',
   'Vainas de Vanilla planifolia curadas durante 6 meses según el método tradicional totonaca. Contenido de vainillina superior al 2%. Aroma floral intenso con notas de higo, caramelo y madera húmeda. La vainilla de Veracruz es reconocida como la mejor del mundo por su perfume complejo.',
   'https://picsum.photos/seed/vainilla-papantla/600/800',
   180.00, '3 vainas (15 g)', 'Especias', true, true),

  (8,
   'Azafrán de La Mancha D.O. Categoría 1',
   'Cooperativa Coopaman',
   'La Mancha, España',
   'Hebras seleccionadas manualmente del Crocus sativus durante la cosecha de otoño. Categoría 1 según ISO 3632, la más alta posible. Intensidad colorante superior a 250 unidades. Un gramo equivale al trabajo de 150-200 flores. El azafrán con mayor valor por peso del mundo.',
   'https://picsum.photos/seed/azafran-mancha/600/800',
   950.00, '2 g', 'Especias', false, true),

  (9,
   'Mezcla de Chiles Oaxaqueños Premium',
   'Casa Maguey',
   'Oaxaca, México',
   'Selección artesanal de chiles secos: ancho, mulato, pasilla negro y chile negro oaxaqueño. Secado al sol y seleccionado a mano en comunidades del Valle de Oaxaca. Base imprescindible para moles, adobos y marinadas. Sin conservadores ni aditivos.',
   'https://picsum.photos/seed/chiles-oaxaca/600/800',
   145.00, '200 g surtido', 'Especias', false, true),

  -- Chocolates
  (10,
   'Chocolate de Origen Chiapas 70%',
   'Cacao Bucarela',
   'Soconusco, Chiapas, México',
   'Bean-to-bar elaborado con cacao criollo y trinitario del Soconusco, una de las regiones cacaoteras más antiguas de Mesoamérica. 70% cacao, tostado medio para conservar notas frutales. Rojo de frutos silvestres, cereza y un final largo y floral. Certificado orgánico.',
   'https://picsum.photos/seed/chocolate-chiapas/600/800',
   195.00, '80 g', 'Chocolates', true, true),

  (11,
   'Valrhona Guanaja Noir 70%',
   'Valrhona',
   'Tain-l''Hermitage, Francia',
   'Couverture icónica de Valrhona creada en 1986. Ensamble de cacaos de Trinidad, Jamaica y Santo Tomé. 70% de cacao mínimo, sin lecitina de soja. Intenso y amargo, con notas de café, regaliz y una acidez vibrante que lo convierte en favorito de pasteleros profesionales.',
   'https://picsum.photos/seed/chocolate-valrhona/600/800',
   320.00, '250 g', 'Chocolates', false, true),

  -- Conservas
  (12,
   'Anchoas del Cantábrico en AOVE',
   'Conservas Ortiz',
   'País Vasco, España',
   'Anchoas de la especie Engraulis encrasicolus capturadas en el Mar Cantábrico con anzuelo, maduradas 18 meses en sal gruesa. Fileteadas a mano y conservadas en aceite de oliva virgen extra. Umami puro, textura sedosa y salinidad equilibrada. Las mejores anchoas de España.',
   'https://picsum.photos/seed/anchoas-ortiz/600/800',
   280.00, '47 g (16 filetes)', 'Conservas', false, true),

  (13,
   'Trufa Negra Melanosporum Entera',
   'Plantin',
   'Périgord, Francia',
   'Tuber melanosporum entera, primera cocción. Cosecha invernal en los bosques de roble del Périgord Negro. Aroma penetrante e inconfundible con notas de tierra mojada, musgo y cacao. Eleva cualquier preparación: pastas, risottos, huevos y salsas. La trufa más cotizada del mundo.',
   'https://picsum.photos/seed/trufa-negra/600/800',
   1150.00, '25 g', 'Conservas', false, true),

  (14,
   'Caviar Osetra Imperial',
   'Caviar de Neuvic',
   'Dordoña, Francia',
   'Hueva de esturión Acipenser gueldenstaedtii criado en las aguas puras del río Dordoña. Granos medianos dorados con reflejos verdes. Sabor a avellana tostada y mantequilla con una cremosidad prolongada. Certificado por el Consejo Internacional de Pesca. El lujo gastronómico definitivo.',
   'https://picsum.photos/seed/caviar-osetra/600/800',
   3800.00, '30 g', 'Conservas', false, true),

  -- Mieles
  (15,
   'Miel de Abeja Melipona Yucatán',
   'Kab Ik',
   'Valladolid, Yucatán, México',
   'Producida por la abeja nativa maya Melipona beecheii, sin aguijón y en peligro de extinción. La miel más escasa de México: cada colmena produce apenas 1-2 litros al año. Textura líquida, color ámbar claro y sabor complejo con acidez natural, notas florales y un ligero retrogusto ahumado.',
   'https://picsum.photos/seed/miel-melipona/600/800',
   690.00, '250 ml', 'Mieles', true, true),

  (16,
   'Miel de Manuka MGO 400+',
   'Comvita',
   'Isla Sur, Nueva Zelanda',
   'Producida por abejas que polinizan el arbusto Leptospermum scoparium en la remota isla sur de Nueva Zelanda. Certificado MGO 400+ por laboratorio independiente. Textura cremosa, sabor robusto con notas de tierra y caramelo oscuro. Reconocida mundialmente por sus propiedades naturales.',
   'https://picsum.photos/seed/miel-manuka/600/800',
   820.00, '250 g', 'Mieles', false, true),

  (17,
   'Miel de Bosque Negro',
   'Schwarzwälder Imkerei',
   'Selva Negra, Alemania',
   'Melada de bosque recolectada en los abetos y hayas de la Schwarzwald. Color caoba oscuro y sabor intenso con notas de pino, madera y regaliz. Rica en minerales y enzimas. Se produce únicamente cuando los pulgones del abeto generan abundante melada, lo que la hace muy escasa.',
   'https://picsum.photos/seed/miel-bosque/600/800',
   445.00, '350 g', 'Mieles', false, true)

on conflict (id) do update set
  nombre      = excluded.nombre,
  productor   = excluded.productor,
  origen      = excluded.origen,
  descripcion = excluded.descripcion,
  imagen      = excluded.imagen,
  precio      = excluded.precio,
  unidad      = excluded.unidad,
  categoria   = excluded.categoria,
  destacado   = excluded.destacado,
  activo      = excluded.activo;

-- Reiniciar secuencia
select setval('productos_cocina_id_seq', (select max(id) from productos_cocina));
